# Generated by Django 5.1.6 on 2025-02-23 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="game",
            old_name="released_date",
            new_name="release_date",
        ),
    ]
