# Generated by Django 5.1.6 on 2025-02-21 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="contact",
        ),
    ]
