# Generated by Django 5.1.6 on 2025-02-21 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0002_remove_student_contact"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="name",
            new_name="Course_name",
        ),
    ]
