# Generated by Django 5.1.6 on 2025-02-21 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0003_rename_name_course_course_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="Course_name",
            new_name="name",
        ),
    ]
